### ISSUE TITLE
More than 6 levels to split into

### ISSUE THREAD

**Issue by mariavd** [markusstraub/mdsplit#6]
Is there some particular limitation to the number of accepted levels to descent into? I have a file with 8 levels, and I would really like to split it for my Obsidian vault. Thanks.

**Comment by markusstraub** [comment]
I implemented the splitting according to the docs which specify that headings are max 6 levels deep: https://spec.commonmark.org/0.30/#atx-headings

But you can override the max heading level easily enough here: [MAX_HEADING_LEVEL = 6](https://github.com/markusstraub/mdsplit/blob/40d1efe0c970c3e9842b496c4c14143801e5be1a/mdsplit.py#L29)

**Comment by mariavd** [comment]
Right, thanks for the clarification.
