### ISSUE TITLE
Gitlab Wiki Usage

### ISSUE THREAD

**Issue by prismv** [markusstraub/mdsplit#7]
- File names should not contain spaces. This is fixed in 81d592510946c68ef069e1cbdd7466680d55ec7b.
- *TODO*: For the Wiki a link syntax `[link](<basename.md>)` does not get the proper MIME type assigned by the server. `.md` needs to be removed. Together with above change such links are served correctly: `[link](basename)`

Assignees: @prismv
Labels: 
Milestone:

**Comment by markusstraub** [comment]
fixed in release 0.4.2
